# Yaml Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)_$(GitVersion_InformationalVersion)

pr: ["master"]

variables:
  ArtifactName: Modules

resources:
  repositories:
    - repository: templates
      type: github
      name: PoshCode/Azure-Pipelines
      ref: refs/tags/1.0.0

jobs:
  - template: GitVersion-job.yml@templates

  - job: Build
    dependsOn: GitVersion
    variables:
      InformationalVersion: $[dependencies.GitVersion.outputs['GitVersion.InformationalVersion']]
    steps:
    - powershell: .\bootstrap.ps1
      displayName: 'Restore pre-requisites'

    - powershell: .\build.ps1 -OutputDirectory $(Build.BinariesDirectory)\$(Build.DefinitionName) -SemVer $(InformationalVersion) -Verbose
      displayName: 'Run build script'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Build Output'
      inputs:
        ArtifactName: $(ArtifactName)
        targetPath: '$(Build.BinariesDirectory)'

  - template: ScriptAnalyzer-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)

  - template: Pester-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)\Tests'