# Yaml Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)_$(GitVersion_InformationalVersion)

pr: ["master"]

variables:
  ArtifactName: $(Build.DefinitionName)

resources:
  repositories:
    - repository: poshcode
      type: github
      endpoint: github # You'll need to define a service connection in your project on Azure
      name: PoshCode/Azure-Pipelines
      ref: refs/tags/3.0.1

jobs:
  - template: GitVersion-job.yml@poshcode

  # using a custom build job because we have two modules
  - job: Build
    pool:
      vmImage: windows-2019
    dependsOn: GitVersion
    variables:
      InformationalVersion: $[dependencies.GitVersion.outputs['GitVersion.InformationalVersion']]

    steps:
    - template: Install-RequiredModule-step.yml@poshcode

    - powershell: ./build.ps1 -OutputDirectory $(Build.BinariesDirectory)/$(Build.DefinitionName) -SemVer $(InformationalVersion) -Verbose
      displayName: 'Run build script'

    - task: PublishPipelineArtifact@1
      displayName: Publish Build Output
      inputs:
        artifactName: $(ArtifactName)
        targetPath: $(Build.BinariesDirectory)/$(Build.DefinitionName)

  - template: ScriptAnalyzer-job.yml@poshcode
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)
      excludeRules: ["PSShouldProcess","PSUseShouldProcessForStateChangingFunctions","PSAvoidUsingDeprecatedManifestFields","PSPossibleIncorrectUsageOfAssignmentOperator"]

  - template: Gherkin-job.yml@poshcode
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)
      specDirectory: '$(Build.SourcesDirectory)/Specs'