name: Module Builder CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitVersion
        id: gitversion
        uses: ./.github/actions/gitversion
      - name: Build Module
        id: build-module
        uses: ./.github/actions/build-module
        with:
          version: ${{ steps.gitversion.outputs.LegacySemVerPadded }}
          destination: ${{github.workspace}}/output
      - name: Combine Configuration
        id: combine
        run: |
          $Metadata, $Configuration = (ConvertFrom-Json -InputObject '${{ steps.build-module.outputs.moduleinfo }}').Where({ $_.Name -eq "Metadata"}, "Split")
          Move-Item (Join-Path $Metadata.ModuleBase Metadata.psm1) $Configuration.ModuleBase
          Remove-Item $Metadata.ModuleBase -Recurse
      - name: Archive Build Output
        uses: actions/upload-artifact@v2
        with:
          name: Configuration
          path: ${{github.workspace}}/output